application: restful-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /api/books.*
  script: controllers.api.books.app

- url: .*
  script: controllers.main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

builtins:
- remote_api: on